### ISSUE TITLE
Design contract interface for tokenomics

### ISSUE THREAD

**Issue by sirnicolaz** [TelediskoDAO/contracts-legacy#51]
**Methods:**
- create an offer
- set vesting
- transfer locked tokens (only by operators)
- transfer free tokens (free: tokens whose offers are expired)
- balance vesting
- balance locked
- balance free
- balance offered

**Events:**
- offer created (from, amount)
- locked transfer (from, to, amount)
- vesting set (to, amount)

https://github.com/TelediskoDAO/projects/issues/40
https://github.com/TelediskoDAO/projects/issues/50
https://github.com/TelediskoDAO/projects/issues/39

**Comment by vrde** [comment]
Closed by #52
